name: Automated Slices to Text

on:
  workflow_dispatch:

jobs:
  automated_slices_to_text_job:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository files
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Install Chrome for Selenium
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      # 4. Install Python dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager
          # If using standard openai:
          pip install openai
          # Or if you have a custom o1-mini package, install that instead.

      # 5. Run the Selenium script to capture screenshots
      - name: Run .github/scripts/move_slices_and_screenshots.py
        run: |
          # If using headless mode, ensure the --headless option is uncommented in your script.
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python .github/scripts/move_slices_and_screenshots.py

      # 6. Upload screenshots as an artifact (optional but recommended)
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/

      # 7. Run the OpenAI script to generate text from screenshots
      - name: Generate text from screenshots
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/automated_slices_to_text.py screenshots/
